version: "3.7"
services:
  my-performance-server:
    networks:
      - private
      - public
    ports:
      - "127.0.0.1:3000:3000"

  postgres:
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - private

networks:
  public:
  private:
