version: "3.7"
services:
  my-performance-server:
    build: .
    image: my-performance-server-api:latest
    environment:
      - TYPEORM_HOST=postgres
      - TYPEORM_USERNAME=${TYPEORM_USERNAME:-my_performance}
      - TYPEORM_PASSWORD_FILE=/run/secrets/my-performance-db-password
      - TYPEORM_DATABASE=${TYPEORM_DATABASE:-my_performance_db}
      - NODE_ENV=production
    container_name: my-performance-server-api
    restart: always
    secrets:
      - my-performance-db-password
    expose:
      - "3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    container_name: my-performance-postgres
    restart: always
    expose:
      - "5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    secrets:
      - my-performance-db-password
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME:-my_performance}
      - POSTGRES_PASSWORD_FILE=/run/secrets/my-performance-db-password
      - POSTGRES_DB=${TYPEORM_DATABASE:-my_performance_db}

volumes:
  db-data:

secrets:
  my-performance-db-password:
    file: .docker-secret-db-password
